using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using LaySumm.Api.Configuration;
using LaySumm.Api.Processing.Models;
using LaySumm.Api.Processing.Summarization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace LaySumm.Api.Processing.Assembly;

public sealed class DocumentAssembler
{
    private readonly BlobServiceClient _blobServiceClient;
    private readonly StorageOptions _storageOptions;
    private readonly ILogger<DocumentAssembler> _logger;

    public DocumentAssembler(BlobServiceClient blobServiceClient, IOptions<StorageOptions> storageOptions, ILogger<DocumentAssembler> logger)
    {
        _blobServiceClient = blobServiceClient;
        _storageOptions = storageOptions.Value;
        _logger = logger;
    }

    public async Task<AssemblyResult> AssembleAsync(
        StructuredDocument document,
        IReadOnlyList<SummarySection> sections,
        IReadOnlyList<GeneratedVisual> visuals,
        CancellationToken cancellationToken)
    {
        var container = _blobServiceClient.GetBlobContainerClient(_storageOptions.ContainerName);
        await container.CreateIfNotExistsAsync(cancellationToken: cancellationToken);

        var basePath = $"pls/{document.DocumentId}/{DateTimeOffset.UtcNow:yyyyMMddHHmmss}";

        var jsonUri = await UploadJsonAsync(container, basePath, document, sections, visuals, cancellationToken);
        var htmlContent = BuildHtml(document, sections, visuals);
        var htmlUri = await UploadTextAsync(container, basePath, "summary.html", htmlContent, cancellationToken);
        var docxUri = await UploadDocxAsync(container, basePath, document, sections, visuals, cancellationToken);
        var pdfUri = await UploadPdfPlaceholderAsync(container, basePath, htmlContent, cancellationToken);

        return new AssemblyResult(jsonUri, htmlUri, docxUri, pdfUri);
    }

    private async Task<Uri> UploadJsonAsync(
        BlobContainerClient container,
        string basePath,
        StructuredDocument document,
        IReadOnlyList<SummarySection> sections,
        IReadOnlyList<GeneratedVisual> visuals,
        CancellationToken cancellationToken)
    {
        var payload = new
        {
            documentId = document.DocumentId,
            fileName = document.FileName,
            metadata = document.Metadata,
            sections = sections.Select(section => new
            {
                section.SectionId,
                section.Title,
                section.PlainLanguageSummary,
                section.WhyItMatters,
                section.Limitations,
                section.Glossary,
                section.Citations
            }),
            visuals = visuals.Select(visual => new
            {
                visual.Prompt,
                visual.Caption,
                visual.AltText,
                assetUri = visual.AssetUri?.ToString()
            })
        };

        var json = JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });
        return await UploadTextAsync(container, basePath, "summary.json", json, cancellationToken);
    }

    private static string BuildHtml(StructuredDocument document, IReadOnlyList<SummarySection> sections, IReadOnlyList<GeneratedVisual> visuals)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!DOCTYPE html>");
        builder.AppendLine("<html lang=\"en\">");
        builder.AppendLine("<head>");
        builder.AppendLine("<meta charset=\"utf-8\" />");
        builder.AppendLine($"<title>Plain-language summary - {document.FileName}</title>");
        builder.AppendLine("<style>body{font-family:Segoe UI,Arial,sans-serif;margin:2rem;}h1{font-size:2rem;}h2{margin-top:1.5rem;}section{margin-bottom:2rem;}figure{margin:1rem 0;}figcaption{font-size:0.9rem;color:#555;}table{border-collapse:collapse;width:100%;}td,th{border:1px solid #ddd;padding:0.5rem;}</style>");
        builder.AppendLine("</head>");
        builder.AppendLine("<body>");
        builder.AppendLine("<header>");
        builder.AppendLine($"<h1>Plain-language summary for {document.FileName}</h1>");
        builder.AppendLine("<p>This summary was generated by LaySumm's agentic workflow with provenance-aware citations.</p>");
        builder.AppendLine("</header>");
        builder.AppendLine("<nav><h2>Table of contents</h2><ol>");
        foreach (var section in sections)
        {
            builder.AppendLine($"<li><a href=\"#{section.SectionId}\">{section.Title}</a></li>");
        }
        builder.AppendLine("</ol></nav>");

        foreach (var section in sections)
        {
            builder.AppendLine($"<section id=\"{section.SectionId}\">");
            builder.AppendLine($"<h2>{section.Title}</h2>");
            builder.AppendLine($"<p>{section.PlainLanguageSummary}</p>");
            if (!string.IsNullOrWhiteSpace(section.WhyItMatters))
            {
                builder.AppendLine($"<h3>Why this matters</h3><p>{section.WhyItMatters}</p>");
            }
            if (!string.IsNullOrWhiteSpace(section.Limitations))
            {
                builder.AppendLine($"<h3>Limitations</h3><p>{section.Limitations}</p>");
            }
            if (!string.IsNullOrWhiteSpace(section.Glossary))
            {
                builder.AppendLine($"<h3>Glossary</h3><p>{section.Glossary}</p>");
            }
            builder.AppendLine("</section>");
        }

        if (visuals.Count > 0)
        {
            builder.AppendLine("<section><h2>Explanatory visuals</h2>");
            foreach (var visual in visuals)
            {
                builder.AppendLine("<figure>");
                if (visual.AssetUri is not null)
                {
                    builder.AppendLine($"<img src=\"{visual.AssetUri}\" alt=\"{visual.AltText}\" style=\"max-width:100%;height:auto;\" />");
                }
                builder.AppendLine($"<figcaption>{visual.Caption}</figcaption>");
                builder.AppendLine("</figure>");
            }
            builder.AppendLine("</section>");
        }

        builder.AppendLine("</body></html>");
        return builder.ToString();
    }

    private async Task<Uri> UploadTextAsync(BlobContainerClient container, string basePath, string fileName, string content, CancellationToken cancellationToken)
    {
        var blobClient = container.GetBlobClient($"{basePath}/{fileName}");
        await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(content));
        await blobClient.UploadAsync(stream, overwrite: true, cancellationToken);
        return blobClient.Uri;
    }

    private async Task<Uri> UploadDocxAsync(
        BlobContainerClient container,
        string basePath,
        StructuredDocument document,
        IReadOnlyList<SummarySection> sections,
        IReadOnlyList<GeneratedVisual> visuals,
        CancellationToken cancellationToken)
    {
        await using var stream = new MemoryStream();
        using (var wordDocument = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
        {
            var mainPart = wordDocument.AddMainDocumentPart();
            mainPart.Document = new Document(new Body());
            var body = mainPart.Document.Body!;

            body.AppendChild(new Paragraph(new Run(new Text($"Plain-language summary for {document.FileName}"))));
            foreach (var section in sections)
            {
                body.AppendChild(new Paragraph(new Run(new Break())));
                body.AppendChild(new Paragraph(new Run(new Text(section.Title))));
                body.AppendChild(new Paragraph(new Run(new Text(section.PlainLanguageSummary))));
                if (!string.IsNullOrWhiteSpace(section.WhyItMatters))
                {
                    body.AppendChild(new Paragraph(new Run(new Text($"Why this matters: {section.WhyItMatters}"))));
                }
                if (!string.IsNullOrWhiteSpace(section.Limitations))
                {
                    body.AppendChild(new Paragraph(new Run(new Text($"Limitations: {section.Limitations}"))));
                }
                if (!string.IsNullOrWhiteSpace(section.Glossary))
                {
                    body.AppendChild(new Paragraph(new Run(new Text($"Glossary: {section.Glossary}"))));
                }
            }

            if (visuals.Count > 0)
            {
                body.AppendChild(new Paragraph(new Run(new Break())));
                body.AppendChild(new Paragraph(new Run(new Text("Visuals"))));
                foreach (var visual in visuals)
                {
                    body.AppendChild(new Paragraph(new Run(new Text($"Prompt: {visual.Prompt}"))));
                    body.AppendChild(new Paragraph(new Run(new Text($"Caption: {visual.Caption}"))));
                }
            }

            mainPart.Document.Save();
        }

        stream.Position = 0;
        var blobClient = container.GetBlobClient($"{basePath}/summary.docx");
        await blobClient.UploadAsync(stream, overwrite: true, cancellationToken);
        return blobClient.Uri;
    }

    private async Task<Uri> UploadPdfPlaceholderAsync(BlobContainerClient container, string basePath, string htmlContent, CancellationToken cancellationToken)
    {
        var placeholderContent = "LaySumm PDF rendering is not available in the offline environment. Refer to the HTML version for full fidelity.\n\n" + htmlContent;
        return await UploadTextAsync(container, basePath, "summary.pdf", placeholderContent, cancellationToken);
    }
}

public sealed record AssemblyResult(Uri JsonUri, Uri HtmlUri, Uri DocxUri, Uri PdfUri);
